name: ParaCL pre-commit and post-push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Install google test, also install g++-10 (for c++20 standart)
      run: sudo apt-get install libgtest-dev googletest googletest-tools google-mock libboost-dev g++-10
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: CMake release config
      run: cmake -S . -B build -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=Release
    - name: CMake release build
      run: cmake --build build
    - name: CMake release test
      run: env CTEST_OUTPUT_ON_FAILURE=1 ctest --test-dir build/e2e
    - name: CMake debug config
      run: cmake -S . -B debug -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=Release
    - name: CMake debug build
      run: cmake --build debug
    - name: CMake debug test
      run: env CTEST_OUTPUT_ON_FAILURE=1 ctest --test-dir build/e2e
