name: ParaCL pre-commit and post-push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Install flex
      run: sudo apt install flex libfl-dev
    - name: Install conan
      run: pip install conan
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Conan profile detect
      run: conan profile detect --force
      
    - name: Conan release requirements install
      run: conan install . --build=missing -s compiler.cppstd=gnu20 -s build_type=Release
    - name: CMake release config
      run: cmake --preset=conan-release -DCMAKE_CXX_COMPILER=g++-10
    - name: CMake release build
      run: cmake --build build/Release
    - name: CMake release tests
      run: env CTEST_OUTPUT_ON_FAILURE=1 ctest --test-dir build/Release/e2e

    - name: Conan debug requirements install
      run: conan install . --build=missing -s compiler.cppstd=gnu20 -s build_type=Debug
    - name: CMake debug config
      run: cmake --preset=conan-debug -DCMAKE_CXX_COMPILER=g++-10
    - name: CMake debug build
      run: cmake --build build/Debug
    - name: CMake debug tests
      run: env CTEST_OUTPUT_ON_FAILURE=1 ctest --test-dir build/Debug/e2e

